CREATE TABLE menu_item
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                   VARCHAR(255),
    price                  DOUBLE PRECISION,
    description            VARCHAR(255),
    image                  VARCHAR(255),
    available_only_on_site BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_menu_item PRIMARY KEY (id)
);

CREATE TABLE restaurant
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    address      VARCHAR(255),
    type_kitchen VARCHAR(255),
    owner        BIGINT,
    CONSTRAINT pk_restaurant PRIMARY KEY (id)
);

CREATE TABLE restaurant_menu_items
(
    restaurant_entity_id BIGINT NOT NULL,
    menu_items_id        BIGINT NOT NULL
);

CREATE TABLE restaurant_schedule_slot
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    day_of_week   VARCHAR(255),
    start_hour    time WITHOUT TIME ZONE,
    end_hour      time WITHOUT TIME ZONE,
    restaurant_id BIGINT,
    CONSTRAINT pk_restaurant_schedule_slot PRIMARY KEY (id)
);

CREATE TABLE user_restaurant
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email               VARCHAR(255),
    password            VARCHAR(255),
    name                VARCHAR(255),
    user_type_entity_id BIGINT,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE user_type
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_user_type PRIMARY KEY (id)
);

ALTER TABLE restaurant_menu_items
    ADD CONSTRAINT uc_restaurant_menu_items_menuitems UNIQUE (menu_items_id);

ALTER TABLE restaurant_schedule_slot
    ADD CONSTRAINT FK_RESTAURANT_SCHEDULE_SLOT_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurant (id);

ALTER TABLE user_restaurant
    ADD CONSTRAINT FK_USER_ON_USERTYPEENTITY FOREIGN KEY (user_type_entity_id) REFERENCES user_type (id);

ALTER TABLE restaurant_menu_items
    ADD CONSTRAINT fk_resmenite_on_menu_item_entity FOREIGN KEY (menu_items_id) REFERENCES menu_item (id);

ALTER TABLE restaurant_menu_items
    ADD CONSTRAINT fk_resmenite_on_restaurant_entity FOREIGN KEY (restaurant_entity_id) REFERENCES restaurant (id);